convoy:
  image: wlan0/meta-convoy
  privileged: true
  pid: host
  net: host
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.dns: 'true'
  environment:
   - CATTLE_URL=$CATTLE_URL
   - CATTLE_ACCESS_KEY=$CATTLE_ACCESS_KEY
   - CATTLE_SECRET_KEY=$CATTLE_SECRET_KEY
